---
# SPDX-FileCopyrightText: 2022 Free Software Foundation Europe e.V. <https://fsfe.org>
# SPDX-FileCopyrightText: 2023 The WAG development team
#
# SPDX-License-Identifier: CC0-1.0
name: Lint the project
on: [push, pull_request]
env:
  CARGO_TERM_COLOR: always
jobs:
  reuse:
    name: Lint with REUSE
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Lint licenses
        uses: fsfe/reuse-action@v3
  clippy:
    name: Lint with Clippy
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Clippy
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - name: Add caching
        uses: Swatinem/rust-cache@v2
      - name: Lint Rust code
        run: cargo clippy --all-targets --all-features -- -D warnings
  cargo-deny:
    name: Lint with cargo-deny
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Lint Rust code
        uses: EmbarkStudios/cargo-deny-action@v1
        with:
          command: check bans licenses sources
  cargo-outdated:
    name: Lint with cargo-outdated
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Add caching
        uses: Swatinem/rust-cache@v2
      - name: Install cargo-outdated
        run: cargo install --locked cargo-outdated
      - name: Lint Rust code
        run: cargo outdated -v
  taplo:
    name: Lint with taplo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install taplo
        uses: uncenter/setup-taplo@v1
      - name: Lint TOML code
        run: taplo lint --verbose **.toml
