# SPDX-FileCopyrightText: 2023 The WAG development team
#
# SPDX-License-Identifier: CC0-1.0

name: Create new release

on:
  push:
    tag:
      - "v**"

jobs:
  github:
    name: Create a Github release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install git-cliff
        uses: taiki-e/install-action@git-cliff
      - name: Generate changelog
        run: git-cliff -o
      - name: Release project
        uses: softprops/action-gh-release@v2
        with:
          body_path: CHANGELOG.md
